service: uaipy-core

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "local"}
  environment: ${file(./config/environments/env.${self:provider.stage}.json)}
  apiGateway:
    apiKeys:
      - device:
          - deviceApiKey
      - client:
          - clientApiKey
    usagePlan:
      - device:
          quota:
            limit: 5000
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 100
      - client:
          quota:
            limit: 5000
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 100
plugins:
  - serverless-plugin-typescript
  - serverless-offline

build:
  esbuild: false

functions:
  getUsersFunction:
    handler: src/infra/functions/user/getUsersFunction.handler

  createUserFunction:
    handler: src/infra/functions/user/createUserFunction.handler
    events:
      - http:
          path: user
          method: POST
          private: true
          cors: false

  helloFunctionFunction:
    handler: src/infra/functions/helloFunction.handler
    events:
      - http:
          private: true
          path: hello
          method: GET
          cors: false
          
  authFunction:
    handler: src/infra/functions/authFunction.handler
    events:
      - http:
          path: auth
          method: POST
          private: true
          cors: false
